### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by Trid-collab** [mattleong/CosmicNvim#15]
I quite liked your setup, especially the telescope support for lsp config.
Could you please add a setup python support say with pyright lang server with organize imports with isort and formatting with black and other parameters which you deem fit.

**Comment by mattleong** [comment]
Hi @Trid-collab,

I'm not sure CosmicNvim is at a point where it can commit to including Python LSP by default (But I'm always open to discussions!). 

I personally don't use it and it's quite easy to add it yourself. Look at `[config/config.lua`](https://github.com/mattleong/CosmicNvim/blob/main/lua/cosmic/config/config.lua#L63) for an example on how to add a non-default LSP server with custom settings.

It would look something similar to this:
```lua
local config = {}
config.lsp.python = {
  opts = {
    -- lsp server options here
    on_attach = function() end,
  }
}
return config
```

**Comment by Trid-collab** [comment]
Thank you. Let me try
Also a  week back I thought I saw a  config for the sumneko_lua in the providers directory, which I didn't see today. Did I miss it . Could you direct me to it.

**Comment by mattleong** [comment]
You are correct, it was removed because lsp-installers config was superior. However, they recently just changed their sumneko_lua default config so I had to bring back some elements from the original provider file. They can now be found in the config defaults [here](https://github.com/mattleong/CosmicNvim/blob/main/lua/cosmic/config/init.lua#L78)
